version: '3.2'

services:
  users:
    build: ./users
    container_name: "users"
    volumes:
      - "./users:/home/app/users"
      - "/home/app/users/node_modules"
    ports:
      - "3030:3030"
    environment:
      - CONTAINER_PORT=${USERS_CONTAINER_PORT}
      - CONTAINER_NAME=${USERS_CONTAINER_NAME}
      - ACCESS_SECRET=${SERVICE_ACCESS_SECRET}
      - CRYPTO_ALGORITHM=${CRYPTO_ALGORITHM}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - DB_SERVER=docker.for.mac.localhost:27017
      - DB_NAME=users