version: '3.2'

services:
  twitter-service:
    build: ./twitter-service
    container_name: "twitter-service"
    volumes:
      - "./twitter-service:/home/app/twitter-service"
      - "/home/app/twitter-service/node_modules"
    ports:
      - "3040:3040"
    environment:
      - CONTAINER_PORT=${TWITTER_SERVICE_CONTAINER_PORT}
      - CONTAINER_NAME=${TWITTER_SERVICE_CONTAINER_NAME}
      - ACCESS_SECRET=${SERVICE_ACCESS_SECRET}
      - CRYPTO_ALGORITHM=${CRYPTO_ALGORITHM}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - DB_SERVER=docker.for.mac.localhost:27017
      - DB_NAME=twitter_service
      - NEO4J_CONNECTION=http://docker.for.mac.localhost:7474
      - NEO4J_AUTH=dev:password
      - TWITTER_CONSUMER_KEY=EgzVLaN1OMNb3EFG5c4SKvcTD
      - TWITTER_CONSUMER_SECRET=U61JRK4OiEd0QGE68V1YXRBCy1GZ4BaIRXxfWDDbsAjSJWuuCa
      - TWITTER_ACCESS_TOKEN_KEY=542907787-qlzjJ4PPPfqxuomiwJdfzxgZ1mMWlSCsQLYt2PVO
      - TWITTER_ACCESS_TOKEN_SECRET=RATtlY9OfDNr3a8mCJToa13swZ6MRzrvlCIru7s21xeLZ
