# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Justin Paul Graber

# Copy custom configuration file from the current directory
COPY . /etc/nginx

ADD index.html /var/www/innosol-client/
